# Generated by Django 4.1.4 on 2023-01-29 18:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_tasks_confirmation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='completness',
        ),
        migrations.CreateModel(
            name='completness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datecompleted', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taskapp.tasks')),
            ],
        ),
    ]
