# Generated by Django 4.1.4 on 2023-01-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0003_remove_tasks_completness_completness'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='completness',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='completness',
        ),
    ]
