# Generated by Django 4.1.4 on 2023-01-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0004_tasks_completion_date_tasks_completness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='expected_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
