# Generated by Django 4.1.4 on 2023-02-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0005_tasks_expected_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='instructions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='instruction/')),
            ],
        ),
        migrations.AddField(
            model_name='tasks',
            name='instructions',
            field=models.ManyToManyField(blank=True, to='taskapp.instructions'),
        ),
    ]
