# Generated by Django 4.1.4 on 2023-02-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0006_instructions_tasks_instructions'),
    ]

    operations = [
        migrations.CreateModel(
            name='resolutiondocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='instruction/')),
            ],
        ),
        migrations.AddField(
            model_name='tasks',
            name='detailsres',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='resolutiondocs',
            field=models.ManyToManyField(blank=True, to='taskapp.resolutiondocs'),
        ),
    ]
