# Generated by Django 4.1.4 on 2023-02-05 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0007_resolutiondocs_tasks_detailsres_tasks_resolutiondocs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructions',
            name='file',
            field=models.FileField(upload_to='instructions/'),
        ),
        migrations.AlterField(
            model_name='resolutiondocs',
            name='file',
            field=models.FileField(upload_to='resdoc/'),
        ),
    ]
