# Generated by Django 4.1.4 on 2023-02-06 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0008_alter_instructions_file_alter_resolutiondocs_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='confirmation_date',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
