# Generated by Django 4.1.4 on 2023-02-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0009_tasks_confirmation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='confirmation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
