# Generated by Django 4.1.4 on 2023-02-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0010_alter_tasks_confirmation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
