# Generated by Django 4.1.4 on 2023-02-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0011_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='content',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
